In [1]:
import numpy as np

In [2]:
# create 1D array 
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
# data type of (arr) array
arr.dtype

dtype('int32')

In [4]:
# shape of the array 
arr.shape

(4,)

In [5]:
# get the value at specific index(3)
arr[3]

4

In [6]:
# creating 2D array 
lstarr=np.array([[1,2,3,4],[5,6,7,8]])
lstarr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# make the 2D array in 1D array
lstarr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
# creating array fill with zeroes
zero=np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# datatype of zeroes arrray is float
zero.dtype

dtype('float64')

In [10]:
# arange(n) generate the number from (0 to n-1)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# reshape the a in 5 rows and 3 column
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [12]:
# making 2D to 1D array
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# equal space b/w each number(here 1 se 3 tk jayege and 12 numbers dega with same difference b/w each numbers)
lspace=np.linspace(1,3,12)
lspace

array([1.        , 1.18181818, 1.36363636, 1.54545455, 1.72727273,
       1.90909091, 2.09090909, 2.27272727, 2.45454545, 2.63636364,
       2.81818182, 3.        ])

In [14]:
# create empty array and fill with random numbers
emp=np.empty((4,2))
emp

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 7.56597770e-307],
       [1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306]])

In [15]:
# create empty array with fill with the value 
em_like=np.empty_like(lspace)
em_like

array([1.        , 1.18181818, 1.36363636, 1.54545455, 1.72727273,
       1.90909091, 2.09090909, 2.27272727, 2.45454545, 2.63636364,
       2.81818182, 3.        ])

In [16]:
# create identity matrix of 5 by 5
ide=np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# create 2D array
arlist=np.array([[1,2,3],[4,5,6],[7,8,9]])
arlist

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# sum of all numbers of array
arlist.sum()

45

In [19]:
# sum of numer of axis 0(sum of each column (axis=0 means column))
arlist.sum(axis=0)

array([12, 15, 18])

In [20]:
# sum of numer of axis 1(sum of each rows (axis=1 means rows))
arlist.sum(axis=1)

array([ 6, 15, 24])

In [21]:
# transpose of matrix(transpose means row become column and column become rows)
arlist.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
# flat use for iterate the number of the array
for i in arlist.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [23]:
# dimension of array(1D,2D,3D...)
arlist.ndim

2

In [24]:
# size of array(number of elements in array)
arlist.size

9

In [25]:
# number of bytes of array 
arlist.nbytes

36

In [26]:
# data types of array
arlist.dtype

dtype('int32')

In [27]:
# create 1D array
nar=np.array([11,2,5,7,1,8,91,21])
nar

array([11,  2,  5,  7,  1,  8, 91, 21])

In [28]:
# print the maximum value
nar.max()

91

In [29]:
# print the index of the maximum value of array 
nar.argmax()

6

In [30]:
# print he minimum value of array
nar.min()

1

In [31]:
# print he index of minimum value
nar.argmin()

4

In [32]:
# give the index after sorting the value
nar.argsort()

array([4, 1, 2, 3, 5, 0, 7, 6], dtype=int64)

In [33]:
# create 2D array
arl=np.array([[4,2,1],[3,0,7],[5,8,6]])
arl

array([[4, 2, 1],
       [3, 0, 7],
       [5, 8, 6]])

In [35]:
# maximum value in 2D array
arl.max()

8

In [36]:
# index of maximum value in 2D array 
arl.argmax()

7

In [37]:
# minimum value of 2D array
arl.min()

0

In [38]:
# index of minimum value of 2D aray
arl.argmin()

4

In [39]:
# give index of maximum value in axis=0(in all column)
arl.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [40]:
# # give index of maximum value in axis=1(in all rows)
arl.argmax(axis=1)

array([0, 2, 1], dtype=int64)

In [127]:
arl


array([[4, 2, 1],
       [3, 0, 7],
       [5, 8, 6]])

In [128]:
arlist

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# sum of 2 array 
arl+arlist

array([[ 5,  4,  4],
       [ 7,  5, 13],
       [12, 16, 15]])

In [42]:
# square root of array 
np.sqrt(arl)

array([[2.        , 1.41421356, 1.        ],
       [1.73205081, 0.        , 2.64575131],
       [2.23606798, 2.82842712, 2.44948974]])

In [43]:
# give the index whose value is > 4 
np.where(arl>4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [44]:
# count the number of non zeroes in array
np.count_nonzero(arl)

8

In [45]:
# print the index of non zeroes value
np.nonzero(arl)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [46]:
# print the size of each item in array
arl.itemsize

4

In [47]:
# count the number of element in array
arl.size

9

In [48]:
# convert array to list
arl.tolist()

[[4, 2, 1], [3, 0, 7], [5, 8, 6]]